### ISSUE TITLE
What should we put here?

### ISSUE THREAD

**Issue by awright18** [Lambda-Cartel/website#1]
I believe this is a jekyll site so can we just add 
Markdown files and do some blogging in this repo for now?  I have my own blog and happy to do that there but didn't know if any project specific blog entries may make since here.  Maybe like the origin story or about or initial challenges,or simply just embedding the youtube videos in separate pages here.

**Comment by yelluw** [comment]
Ive uploaded an initial design to have all the relevant links. Its missing info. I wanted to get it out of the way to focus on Nikeza. next week I'll more content pages or link to the charter. :)

**Comment by yelluw** [comment]
I have defined the following:

- Logo

- Slogan

- Mission statement

- Members bio (with links to their pages)

I dont think anything else is needed atm.

**Comment by BryanWilhite** [comment]
@yelluw well done! Elegant. Succinct.

A responsive hero image might come to you later. I need one of these myself :)

**Comment by yelluw** [comment]
Thanks!

New design should go up during weekend :)

**Comment by yelluw** [comment]
New design is partially up. Missing members bio info. Will focus on collecting the info in order to finish this. :)

**Comment by yelluw** [comment]
Members info is now up. Gonna work now on adding more stuff. :)

**Comment by yelluw** [comment]
Closing issue and opening new ones as required.
